### ISSUE TITLE
Docs broken

### ISSUE THREAD

**Issue by jkozdon** [climate-machine/RootSolvers.jl#9]
The [docs linked](https://climate-machine.github.io/RootSolvers.jl/latest/) to in the readme seemed to be broken

**Comment by charleskawczynski** [comment]
Yeah, I haven't set them up yet

**Comment by charleskawczynski** [comment]
Hmm, #15 didn’t seem to fix this

**Comment by charleskawczynski** [comment]
Fixed by #20
